name: dart_demo_livescore
description: dart livescore demo.
# version: 1.0.0
#homepage: https://migratorydata.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  migratorydata_client_dart_v6: ^1.0.2

dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  pedantic: ^1.9.0
